name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t flask_app .cd /home/ubuntu/Task/Task10
          docker tag flask_app:latest ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask_app:latest

      - name: Deploy to EC2
        run: |
          # Save the PEM file to a temporary file
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/your-key.pem
          chmod 600 /tmp/your-key.pem

          # Connect to EC2 and deploy the container
          ssh -o StrictHostKeyChecking=no -i /tmp/your-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
          docker stop $(docker ps -q)
          docker run -d -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
          EOF
