name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r Task/Task10/requirements.txt

    - name: Test the application
      run: python -m unittest discover Task/Task10

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4  # Ensure this version is correct
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/Task/Task10 || { echo "Directory not found"; exit 1; }
          git pull origin main || { echo "Failed to pull from git"; exit 1; }
          docker build -t flask-app . || { echo "Docker build failed"; exit 1; }
          docker stop flask-app-container || true
          docker rm flask-app-container || true
          docker run -d -p 80:5000 --name flask-app-container flask-app || { echo "Docker run failed"; exit 1; }
        EOF
