# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build Docker image
      run: |
        docker build -t my-flask-app .

    - name: Run tests
      run: |
        # Replace this with actual test commands if you have any
        echo "No tests specified"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.muhammedaslam2002 }}
        password: ${{ secrets.Aslam@2002 }}

    - name: Push Docker image
      run: |
        docker tag my-flask-app ${{ secrets.muhammedaslam2002 }}/my-flask-app:latest
        docker push ${{ secrets.muhammedaslam2002 }}/my-flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      uses: appleboy/drone-ssh@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.muhammedaslam2002 }}/my-flask-app:latest
          docker stop my-flask-app || true
          docker rm my-flask-app || true
          docker run -d -p 5000:5000 --name my-flask-app ${{ secrets.muhammedaslam2002 }}/my-flask-app:latest

      
